services:
  djangoserver:
    container_name: backend
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3 # Mount the database file to the container

  redis:
    image: redis:7.0
    container_name: redis

  celery:
    container_name: celery
    build: .
    command: celery -A TaskManager worker -l INFO
    restart: always
    depends_on:
      - redis
      - djangoserver
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3 # Mount the database file to the container
