apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: distritask-ns
data:
  my.cnf: |
    [mysqld]
    pid-file=/var/lib/mysql/mysql.pid
    host_cache_size=0
    max_connections=200
    innodb_buffer_pool_size=256M
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    
    [mysql]
    default-character-set=utf8mb4
    
    [client]
    default-character-set=utf8mb4
